const fs = require('fs');
let code = fs.readFileSync('src/components/ProjectGalleryGoldenHeights.tsx', 'utf8');

code = code.replace(
  `        <div className="flex flex-col md:flex-row justify-between items-center md:items-end gap-6 text-center md:text-left">\n          <motion.div\n            initial={{ opacity: 0, y: 20 }}\n            whileInView={{ opacity: 1, y: 0 }}\n            viewport={{ once: true }}\n            className="flex items-center justify-center md:justify-start gap-4 mb-4"\n          >\n            <div className="w-8 h-[1px] bg-gold"></div>\n            <h2 className="text-gold font-medium tracking-widest uppercase text-sm">PROJECT GALLERY</h2>\n            <div className="w-8 h-[1px] bg-gold"></div>\n          </motion.div>\n          <motion.h3\n            initial={{ opacity: 0, y: 20 }}\n            whileInView={{ opacity: 1, y: 0 }}\n            viewport={{ once: true }}\n            transition={{ delay: 0.1 }}\n            className="text-4xl md:text-5xl font-extrabold tracking-tight text-white"\n          >\n            Explore <span className="text-gold-accent">Golden Heights</span>\n          </motion.h3>\n        </div>\n        <motion.div\n          initial={{ opacity: 0, x: 20 }}\n          whileInView={{ opacity: 1, x: 0 }}\n          viewport={{ once: true }}\n          transition={{ delay: 0.2 }}\n        >\n          <button \n            onClick={() => navigate('/projects/golden-heights/gallery')}\n            className="inline-flex items-center justify-center gap-2 px-6 py-3 rounded-full border border-gold/40 text-gold hover:text-white hover:bg-gold/10 hover:border-gold hover:shadow-[0_0_20px_rgba(200,164,106,0.3)] transition-all duration-300 font-medium text-sm"\n          >\n            View All <ArrowRight className="w-4 h-4" />\n          </button>\n        </motion.div>\n      </div>\n      </div>`,
  `        <div className="flex flex-col md:flex-row justify-between items-center md:items-end gap-6 text-center md:text-left">\n          <div>\n            <motion.div\n              initial={{ opacity: 0, y: 20 }}\n              whileInView={{ opacity: 1, y: 0 }}\n              viewport={{ once: true }}\n              className="flex items-center justify-center md:justify-start gap-4 mb-4"\n            >\n              <div className="w-8 h-[1px] bg-gold"></div>\n              <h2 className="text-gold font-medium tracking-widest uppercase text-sm">PROJECT GALLERY</h2>\n              <div className="w-8 h-[1px] bg-gold"></div>\n            </motion.div>\n            <motion.h3\n              initial={{ opacity: 0, y: 20 }}\n              whileInView={{ opacity: 1, y: 0 }}\n              viewport={{ once: true }}\n              transition={{ delay: 0.1 }}\n              className="text-4xl md:text-5xl font-extrabold tracking-tight text-white"\n            >\n              Explore <span className="text-gold-accent">Golden Heights</span>\n            </motion.h3>\n          </div>\n          <motion.div\n            initial={{ opacity: 0, x: 20 }}\n            whileInView={{ opacity: 1, x: 0 }}\n            viewport={{ once: true }}\n            transition={{ delay: 0.2 }}\n          >\n            <button \n              onClick={() => navigate('/projects/golden-heights/gallery')}\n              className="inline-flex items-center justify-center gap-2 px-6 py-3 rounded-full border border-gold/40 text-gold hover:text-white hover:bg-gold/10 hover:border-gold hover:shadow-[0_0_20px_rgba(200,164,106,0.3)] transition-all duration-300 font-medium text-sm"\n            >\n              View All <ArrowRight className="w-4 h-4" />\n            </button>\n          </motion.div>\n        </div>\n      </div>`
);

fs.writeFileSync('src/components/ProjectGalleryGoldenHeights.tsx', code);
